spring.profiles.active: dev

# 综合配置
spring:
    datasource:
        driver-class-username: com.mysql.jdbc.Driver

    # Show or not log for each sql query
    # auto :validate or update
    jpa:
        show-sql: true
        properties:
          hibernate:
            hbm2ddl:
              auto: update


---
# 开发环境
# examonlineuser SOAPass@2017
spring:
    profiles: dev
    datasource:
        url: jdbc:mysql://localhost:3306/housekeeping
        username: root
        password: root

server:
    port: 8080

spring.jpa.show-sql: false

endpoints:
  shutdown:
    enabled: true
    sensitive: false
